#!/bin/bash

export GIT_LABS_URL="https://gitlab.com/Tatiana239/spbspu-labs-source.git"
export GIT_TESTS_URL="https://github.com/TanyaKovalenko/Tests.git"
export GITLAB_PROJECT_PATH="Tatiana239/spbspu-labs-source"
export BRANCH_SPECIFIER="origin/master"
export TARGET_BRANCH_REGEX="*buggy-implementation.*"
export CRONTAB_LINE="* * * * *"
export AUTO_ClOSE_FAILED="true"
export AUTO_MERGE_PASSED="true"
export SCM_SCHEDULE="*/1 * * * *"
export EXECUTE_SHELL_COMMAND="./script.sh"
export RECIPIENT_LIST="tanyakovalenko1994@gmail.com" 
export ATTACH_BUILD_LOG="false"
export PROJECT_DEFAULT_SUBJECT="\$PROJECT_DEFAULT_SUBJECT" 
export PROJECT_DEFAULT_CONTENT="\$PROJECT_DEFAULT_CONTENT"
export PROJECT_DEFAULT_REPLYTO="\$PROJECT_DEFAULT_REPLYTO"
export DEFAULT_SUBJECT="\$DEFAULT_SUBJECT"
export DEFAULT_PRESEND_SCRIPT="\$DEFAULT_PRESEND_SCRIPT"
export DEFAULT_REPLYTO="\$DEFAULT_REPLYTO"
